//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areaStock
    {
        public int id { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idEquipo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaUltimoServicio { get; set; }
        public string numeroSerie { get; set; }
    }
}
