//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        public int id { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public string url { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fcreo { get; set; }
        public string creo { get; set; }
        public string modifico { get; set; }
        public Nullable<System.DateTime> fmodifico { get; set; }
    }
}
