//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        public int incidenciaID { get; set; }
        public string usuario { get; set; }
        public int equipoID { get; set; }
        public Nullable<bool> serializado { get; set; }
        public string numSerie { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activa { get; set; }
        public Nullable<System.DateTime> fechaAperrtura { get; set; }
        public Nullable<System.DateTime> fechaAtencion { get; set; }
        public Nullable<System.DateTime> fechaClaususa { get; set; }
        public Nullable<bool> abierta { get; set; }
    }
}
