//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public Nullable<int> idRecord { get; set; }
        public string tabla { get; set; }
        public Nullable<int> usuario { get; set; }
        public string evento { get; set; }
        public string valOld { get; set; }
        public string valNew { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string pagina { get; set; }
        public string tipo { get; set; }
    }
}
