//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisicione
    {
        public int requisicionID { get; set; }
        public Nullable<int> idRequisitor { get; set; }
        public Nullable<int> idResuelve { get; set; }
        public string descripcion { get; set; }
        public string respuesta { get; set; }
        public string estatus { get; set; }
    }
}
