//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int rolID { get; set; }
        public string rol { get; set; }
        public Nullable<int> creo { get; set; }
        public Nullable<System.DateTime> fCreo { get; set; }
        public Nullable<int> modifico { get; set; }
        public Nullable<System.DateTime> fModifico { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
