//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solucione
    {
        public int solucionID { get; set; }
        public int incidenciaID { get; set; }
        public string solucion { get; set; }
        public bool funciono { get; set; }
        public int contador { get; set; }
        public string usuario { get; set; }
    }
}
