//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suspencione
    {
        public int suspencionID { get; set; }
        public int incidenciaID { get; set; }
        public string comentario { get; set; }
        public System.DateTime fechaApertura { get; set; }
        public System.DateTime fechaClausura { get; set; }
        public bool activa { get; set; }
    }
}
