//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareasCheck
    {
        public int idTarea { get; set; }
        public string nombreTarea { get; set; }
        public Nullable<bool> activo { get; set; }
        public string creo { get; set; }
        public Nullable<System.DateTime> fcreo { get; set; }
        public string modifico { get; set; }
        public Nullable<System.DateTime> fmodifico { get; set; }
    }
}
